### PR TITLE
Initial Copy/Paste From Sales-Engineering Repo

### PR DESCRIPTION
**Pull request by daileykluck**

### CODE REVIEW

**Review by fivetran-alexshaffer — APPROVED** [review]
LGTM

**Review by angel-hernandez91 — APPROVED** [review]
lgtm

**Comment by crw** [comment]
There are API keys and secrets that were committed that should be rotated. 

`.DS_Store` should be added to `.gitignore` and removed from the repository.

**Comment by crw** [comment]
I'd actually advise moving the config details (API key and secret) out of those files completely, and including the config from either ENV vars or some external config file that is not included in the repo (you can always include a `creds.py.sample` file to show the expected format.)

**Pull request merged**
